services:
  phpapp1:
    container_name: php-instance
    image: phpapp
    ports:
      - "80:80"
  mysqlapp1:
    container_name: mysql-instance
    image: mysqlapp
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=appdb